insert into subjects (subject_name, tutor) values ('Fashion Design','Bentlee');
insert into subjects (subject_name, tutor) values ('Occupational Therapy','Ludwig');
insert into subjects (subject_name, tutor) values ('Economics','Bogey');
insert into subjects (subject_name, tutor) values ('Oil and Gas Management','Travus');
insert into subjects (subject_name, tutor) values ('Food Science','Trenton');
insert into subjects (subject_name, tutor) values ('Education','Arthur');
insert into subjects (subject_name, tutor) values ('Medical Technology','Courtney');
insert into subjects (subject_name, tutor) values ('Sociology','Neale');
insert into subjects (subject_name, tutor) values ('Film Studies','Tan');
insert into subjects (subject_name, tutor) values ('Veterinary Medicine','Salvatore');
insert into subjects (subject_name, tutor) values ('Classics and Ancient History','Sky');
insert into subjects (subject_name, tutor) values ('Archaeology','Jessee');
insert into subjects (subject_name, tutor) values ('Biological Sciences','Edvard');
insert into subjects (subject_name, tutor) values ('Interior Design','Augie');
insert into subjects (subject_name, tutor) values ('Law','Omero');
insert into subjects (subject_name, tutor) values ('History','Gradeigh');
insert into subjects (subject_name, tutor) values ('Human Resources Management','Artemas');
insert into subjects (subject_name, tutor) values ('Film Making','Turner');
insert into subjects (subject_name, tutor) values ('Business and Management Studies','Rafi');
insert into subjects (subject_name, tutor) values ('Art','Kellen');
insert into subjects (subject_name, tutor) values ('Pharmacy','Barr');
insert into subjects (subject_name, tutor) values ('Electrical and Electronic Engineering','Cullen');
insert into subjects (subject_name, tutor) values ('Film Production','Chane');
insert into subjects (subject_name, tutor) values ('Hospitality Leisure Recreation and Tourism','Farris');
insert into subjects (subject_name, tutor) values ('Robotics','Elton');
insert into subjects (subject_name, tutor) values ('Geography and Environmental Sciences','Morrie');
insert into subjects (subject_name, tutor) values ('American Studies','Gaylor');
insert into subjects (subject_name, tutor) values ('Chemical Engineering','Wendel');
insert into subjects (subject_name, tutor) values ('Anthropology','Wolfy');
insert into subjects (subject_name, tutor) values ('Geography','Dale');
insert into subjects (subject_name, tutor) values ('Youth Work','Saunders');
insert into subjects (subject_name, tutor) values ('Liberal Arts','Leroy');
insert into subjects (subject_name, tutor) values ('Accounting and Finance','Chester');
insert into subjects (subject_name, tutor) values ('Floristry','Levey');
insert into subjects (subject_name, tutor) values ('Dentistry','Alfredo');
insert into subjects (subject_name, tutor) values ('Hotel Management','Dennet');
insert into subjects (subject_name, tutor) values ('Linguistics','Niccolo');
insert into subjects (subject_name, tutor) values ('Master of Laws','Boy');
insert into subjects (subject_name, tutor) values ('Creative Writing','Antoni');
insert into subjects (subject_name, tutor) values ('Education Studies','Pancho');
insert into subjects (subject_name, tutor) values ('Agriculture','Jerry');
insert into subjects (subject_name, tutor) values ('Biotechnology','Rik');
insert into subjects (subject_name, tutor) values ('Anatomy and Physiology','Padgett');
insert into subjects (subject_name, tutor) values ('Physiotherapy','Elias');
insert into subjects (subject_name, tutor) values ('Drama Dance and Cinematics','Kristo');
insert into subjects (subject_name, tutor) values ('Information Technology','Brook');
insert into subjects (subject_name, tutor) values ('Animation','Clevie');
insert into subjects (subject_name, tutor) values ('Business and Management','Marvin');
insert into subjects (subject_name, tutor) values ('Criminology','Myrwyn');
insert into subjects (subject_name, tutor) values ('Medicine','Adelbert');
insert into subjects (subject_name, tutor) values ('History of Art Architecture and Design','Beniamino');
insert into subjects (subject_name, tutor) values ('International Relations','Corey');
insert into subjects (subject_name, tutor) values ('Building','Meryl');
insert into subjects (subject_name, tutor) values ('Dance','Ellery');
insert into subjects (subject_name, tutor) values ('Computer Science','Rudie');
insert into subjects (subject_name, tutor) values ('English','Sandor');
insert into subjects (subject_name, tutor) values ('Materials Technology','Geoffry');
insert into subjects (subject_name, tutor) values ('English Literature','Hanson');
insert into subjects (subject_name, tutor) values ('Oil and Gas Engineering','Rodolph');
insert into subjects (subject_name, tutor) values ('Air Transport Management','Jeremie');
insert into subjects (subject_name, tutor) values ('Media and Communications','Alix');
insert into subjects (subject_name, tutor) values ('Sports Science','Holmes');
insert into subjects (subject_name, tutor) values ('Philosophy','Tore');
insert into subjects (subject_name, tutor) values ('Social Work','Dicky');
insert into subjects (subject_name, tutor) values ('Fashion','Skelly');
insert into subjects (subject_name, tutor) values ('Design and Crafts','Mohammed');
insert into subjects (subject_name, tutor) values ('Forensic Science','Krishna');
insert into subjects (subject_name, tutor) values ('Engineering','Clemmie');
insert into subjects (subject_name, tutor) values ('Psychology','Sal');
insert into subjects (subject_name, tutor) values ('Physics and Astronomy','Radcliffe');
insert into subjects (subject_name, tutor) values ('Bachelor of Laws','Nigel');
insert into subjects (subject_name, tutor) values ('Aerospace Engineering','Brocky');
insert into subjects (subject_name, tutor) values ('Social Policy','Noland');
insert into subjects (subject_name, tutor) values ('Land and Property Management','Neddy');
insert into subjects (subject_name, tutor) values ('Hospitality and Tourism','Briggs');
insert into subjects (subject_name, tutor) values ('Music','Cristiano');
insert into subjects (subject_name, tutor) values ('Communication and Media Studies','Falkner');
insert into subjects (subject_name, tutor) values ('Mathematics','Korey');
insert into subjects (subject_name, tutor) values ('General Engineering','Horton');
insert into subjects (subject_name, tutor) values ('Pharmacology and Pharmacy','Papageno');
insert into subjects (subject_name, tutor) values ('Supply Chain and Logistics','Anselm');
insert into subjects (subject_name, tutor) values ('Geology','Merrill');
insert into subjects (subject_name, tutor) values ('Aeronautical and Manufacturing Engineering','Russell');
insert into subjects (subject_name, tutor) values ('Journalism','Lowell');
insert into subjects (subject_name, tutor) values ('Agriculture and Forestry','Lynn');
insert into subjects (subject_name, tutor) values ('Nursing','Selig');
insert into subjects (subject_name, tutor) values ('Civil Engineering','Rodge');
insert into subjects (subject_name, tutor) values ('Marketing','Blaine');
insert into subjects (subject_name, tutor) values ('Counselling','Meir');
insert into subjects (subject_name, tutor) values ('Development Studies','Rawley');
insert into subjects (subject_name, tutor) values ('Digital Media','Eric');
insert into subjects (subject_name, tutor) values ('Architecture and Environmental Design','Lauritz');
insert into subjects (subject_name, tutor) values ('Politics','Cooper');
insert into subjects (subject_name, tutor) values ('Complementary Medicine','Jethro');
insert into subjects (subject_name, tutor) values ('Mechanical Engineering','Anatol');
insert into subjects (subject_name, tutor) values ('Art and Design','Cort');
insert into subjects (subject_name, tutor) values ('Architecture','Lek');
insert into subjects (subject_name, tutor) values ('TESOL','Iosep');
insert into subjects (subject_name, tutor) values ('Health And Social Care','Nev');
insert into subjects (subject_name, tutor) values ('Chemistry','Kingsley');